on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 10 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish_docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Log in to Docker
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build image
        run: docker build --tag ghcr.io/meziantou/timemachine-samba:1.0.${{github.run_number}} --tag ghcr.io/meziantou/timemachine-samba:latest --file Dockerfile .
        
      - name: push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/meziantou/timemachine-samba:1.0.${{github.run_number}}
          docker push ghcr.io/meziantou/timemachine-samba:latest
